import fs from 'fs';
import net from 'net';
import crypto from 'crypto';
import dotenv from 'dotenv';
import logger from '../utils/logger.js';

export interface FirstRunEnv { host: string; adminApiKey: string; observationApiKey: string }
export class BindRefusedError extends Error {}
export class KeyWriteError extends Error {}

/** CX-3: one precedence rule — a NON-EMPTY launch env wins; else a non-empty
 *  dotenv.parse'd .env value; else none. Deliberately NOT dotenv's own
 *  presence-wins-even-empty load rule: a service manager supplying an empty
 *  ADMIN_API_KEY= must not shadow a valid .env key (it would regenerate a new
 *  key every restart). */
export function resolveAdminKey(envPath: string, processEnvValue: string | undefined):
    { key: string; source: 'env' | 'file' | 'none' } {
  if (processEnvValue) return { key: processEnvValue, source: 'env' };
  try {
    const parsed = dotenv.parse(fs.readFileSync(envPath, 'utf8'));
    if (parsed.ADMIN_API_KEY) return { key: parsed.ADMIN_API_KEY, source: 'file' };
  } catch { /* no file = no file key */ }
  return { key: '', source: 'none' };
}

export function generateAdminKey(): string {
  return crypto.randomBytes(32).toString('hex');
}

export function ensureAdminKey(envPath: string, env: FirstRunEnv): { key: string; generated: boolean } {
  // env.adminApiKey is the caller's already-resolved launch value (config reads
  // process.env post-dotenv). Consulting process.env here directly would let the
  // transitive dotenv.config() side effect (logger → config) shadow the envPath
  // argument — resolveAdminKey's processEnvValue parameter is the one channel.
  const resolved = resolveAdminKey(envPath, env.adminApiKey);
  if (resolved.key) return { key: resolved.key, generated: false };
  const key = generateAdminKey();
  const line = `ADMIN_API_KEY=${key}`;
  const comment = '# generated by KOPENG first run — see SECURITY.md';
  const tmpPath = envPath + '.tmp';
  try {
    let content = '';
    try { content = fs.readFileSync(envPath, 'utf8'); } catch { /* absent → create */ }
    if (/^ADMIN_API_KEY=[ \t]*$/m.test(content)) {
      content = content.replace(/^ADMIN_API_KEY=[ \t]*$/m, line);
    } else {
      if (content.length > 0 && !content.endsWith('\n')) content += '\n';
      content += `${comment}\n${line}\n`;
    }
    // tmp-then-rename (the CX-12 discipline): a crash mid-write must never
    // leave a truncated .env, which holds every other operator setting too.
    // mode 0o600 on create + chmod on the renamed file: the key is the only
    // control in front of corpus writes, so it must not be world-readable on
    // a shared POSIX host. chmod is best-effort — Windows largely ignores it.
    fs.writeFileSync(tmpPath, content, { encoding: 'utf8', mode: 0o600 });
    fs.renameSync(tmpPath, envPath);
    try { fs.chmodSync(envPath, 0o600); } catch { /* Windows / restrictive FS */ }
  } catch (err) {
    try { fs.rmSync(tmpPath, { force: true }); } catch { /* best-effort cleanup */ }
    throw new KeyWriteError(
      `Cannot write ${envPath} to store the generated admin key (${(err as Error).message}). ` +
      `KOPENG does not run keyless: set ADMIN_API_KEY in .env or the environment, then restart.`);
  }
  return { key, generated: true };
}

/** CX-4: loopback iff localhost | ::1 | a REAL v4 address with first octet 127.
 *  net.isIP guards the hostname bypass (127.example.test is NOT loopback). */
export function isLoopbackHost(host: string): boolean {
  if (host === 'localhost' || host === '::1') return true;
  return net.isIP(host) === 4 && host.startsWith('127.');
}

export function assertBindAllowed(env: FirstRunEnv): void {
  if (isLoopbackHost(env.host)) return;
  const missing = [
    ...(env.adminApiKey ? [] : ['ADMIN_API_KEY']),
    ...(env.observationApiKey ? [] : ['OBSERVATION_API_KEY']),
  ];
  if (missing.length === 0) return;
  throw new BindRefusedError(
    `Refusing to bind ${env.host}: non-loopback binds require BOTH keys and ` +
    `${missing.join(' and ')} ${missing.length > 1 ? 'are' : 'is'} not set. ` +
    `Remote deployment is unsupported for the 0.x preview — see SECURITY.md. ` +
    `Set HOST=127.0.0.1 (default) or set the missing key(s).`);
}

export function runFirstRunPreflight(envPath: string, env: FirstRunEnv): { generated: boolean } {
  // Refuse BEFORE generating (team-review fix): the bind check runs against the
  // RESOLVED key state, so a non-loopback bind with a missing ADMIN_API_KEY
  // produces the documented refusal instead of silently minting a fresh key and
  // binding wide — and a refused boot persists nothing. Loopback (the default)
  // never refuses, so first-run generation there is unaffected.
  const resolved = resolveAdminKey(envPath, env.adminApiKey);
  assertBindAllowed({ ...env, adminApiKey: resolved.key });
  const { key, generated } = ensureAdminKey(envPath, env);
  env.adminApiKey = key;
  process.env.ADMIN_API_KEY = key;
  if (generated) logger.info('Admin key generated into .env (first run) — clients pick it up on next start');
  return { generated };
}
